Repository Gibbo3771/pim-tracker, pull requests merged in 2019-04, with the labels that each got.

#15 Feature/crime list view
  client/src/views/crime_item_view.js
  client/src/views/crime_list_view.js
Labels: feature, must have, mvp

#14 Feature/modal
  .jshintignore
  .jshintrc
  .travis.yml
  client/public/css/main.css
  client/src/helpers/pub_sub.js
  client/src/views/modal/modal_view.js
  client/src/views/modal/modal_view_spec.js
  package-lock.json
  package.json
Labels: feature

#37 Feature/refactor map view
  client/src/app.js
  client/src/app_container.js
  client/src/helpers/beautiful_latlng_shapes.js
  client/src/helpers/request_helper.js
  client/src/views/map_view.js
  client/src/views/map_view/map_view.js
Labels: Refactor
